Move currentScore and currentQuestion to localStorage
mayamolodec/Quiz-d-astronomie pull request #6
Opened 2024-12-26 15:21 UTC by mayamolodec

This commit creates two keys in localStorage: 
**currentScore** and **curentQuestion**. 
This info is now stored there.

2025-01-03 17:39 UTC, mayamolodec commented
This commit creates a new file for the **state** object,
stored in a localStorage, and declares a set of functions 
in this file to manage the **state** object's properties. 
This is not the final version; it is just an intermediate check-up.

2025-01-04 10:04 UTC, w1n732mu73 requested changes
Please move the array of questions to your storage.js  file

2025-01-04 10:04 UTC, w1n732mu73 commented on scripts/storage.js
> +    return state.currentQuestion;
That's wrong. You should return an object of question here. Like this 
```suggestion
   return questions[state.currentQuestion];
```

2025-01-05 12:48 UTC, mayamolodec commented on scripts/storage.js
> +    return state.currentQuestion;
Sure! May I make another function then, 
to get the index of the current question?

2025-01-05 13:31 UTC, mayamolodec commented
This commit moves questions array to the storage.js file,
changes getQuestion() and adds getQuestionIndex().

2025-01-15 21:09 UTC, mayamolodec commented
This commit limits access from main.js to the **question** object and 
the **state** object to the functions kept in the storage.js.

Next big change (with the second quiz) is also in work.

2025-01-18 20:12 UTC, w1n732mu73 reviewed
Not bad. You can merge this PR right after you make fixes

2025-01-18 20:12 UTC, w1n732mu73 commented on scripts/main.js
> +    showQuestion(firstQuestion);
```suggestion
    showQuestion(getQuestion());
```

2025-01-18 20:12 UTC, w1n732mu73 commented on scripts/main.js
> +    questionText.textContent = getQuestionText(question);
That't too complicated. You only need  use ` question.text `here

2025-01-21 16:59 UTC, mayamolodec commented on scripts/main.js
> +    showQuestion(firstQuestion);
Sure, I'll fix that!

2025-01-21 16:59 UTC, mayamolodec commented on scripts/main.js
> +    questionText.textContent = getQuestionText(question);
Oh, yes, sure!

2025-01-21 19:17 UTC, mayamolodec commented on scripts/main.js
> +    questionText.textContent = getQuestionText(question);
And should I do the same for the image? Supprimer function `getImage` and just write `question.img_link`?
I did it by functions to not let main.js to question object fields.

2025-01-22 15:59 UTC, mayamolodec commented
This commit fixes the reviewed problems.

2025-01-22 19:27 UTC, w1n732mu73 commented on scripts/storage.js
> +function getAnswers(question){
That does nothing)

2025-01-22 19:27 UTC, w1n732mu73 commented on scripts/main.js
> +    questionText.textContent = getQuestionText(question);
Yes. If you already have an object you can access its fields directly in most cases

2025-01-22 21:26 UTC, mayamolodec commented on scripts/storage.js
> +function getAnswers(question){
Sorry, I'll remove that

2025-01-22 21:26 UTC, mayamolodec commented
This commit deletes unnecessary functions.

2025-01-23 19:05 UTC, merged